import = [
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    # "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
    "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
startup_mode = "Maximized"
decorations = "none"

[font]
normal.family = "CaskaydiaCove Nerd Font"
size = 15 
