require("tc.launch")
require("tc.options")
require("tc.keymaps")
require("tc.autocmds")

spec("tc.colorscheme")
spec("tc.devicons")
spec("tc.treesitter")
spec("tc.mason")
spec("tc.schemastore")
spec("tc.lspconfig")
spec("tc.cmp")
spec("tc.whichkey")
spec("tc.comment")
spec("tc.telescope")
spec("tc.nvim-tree")
spec("tc.lualine")
spec("tc.none-ls")
spec("tc.harpoon")
spec("tc.autopairs")
spec("tc.gitsigns")
spec("tc.neogit")
spec("tc.project")
spec("tc.indentline")

-- Linter (dev)
-- spec("tc.nvim-lint")

-- Format (dev)
-- spec("tc.conform")

spec("tc.extras.copilot")
spec("tc.extras.neoscroll")
spec("tc.extras.fidget")
spec("tc.extras.dressing")
spec("tc.extras.todo-comments")
spec("tc.extras.ufo")
spec("tc.extras.neotab")
spec("tc.extras.colorizer")
-- spec("tc.extras.neotest")

require("tc.lazy")
